config:
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 10MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
    [OUTPUT]
        Name opensearch
        Match kube.*
        Host opensearch-cluster-master-headless.opensearch
        Port 9200
        HTTP_User admin
        HTTP_Passwd admin
        tls On
        tls.verify Off
        Logstash_Format On
        Retry_Limit False
        Index kubernetes-logs
        Replace_Dots    On
        Suppress_Type_Name On
        Trace_Output On
        Trace_Error On

    [OUTPUT]
        Name opensearch
        Match host.*
        Host opensearch-cluster-master-headless.opensearch
        Port 9200
        HTTP_User admin
        HTTP_Passwd admin
        tls On
        tls.verify Off
        Logstash_Format On
        Logstash_Prefix node
        Retry_Limit False
        Index kubernetes-logs
        Replace_Dots    On
        Suppress_Type_Name On
        Trace_Output On
        Trace_Error On