---
controller:
  ingressClassResource:
    name: egress-nginx
  admissionWebhooks:
    enabled: false
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
  watchIngressWithoutClass: true
  extraArgs:
    ingress-class: egress-nginx